# Generated by Django for the Pack model
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ("annales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pack",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.PositiveIntegerField()),
                ("discount_percent", models.PositiveIntegerField(default=0)),
                ("image", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="pack",
            name="annales",
            field=models.ManyToManyField(related_name="packs", to="annales.Annale"),
        ),
    ]
