# Generated by Django for the Review model
from django.db import migrations, models
import uuid
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("annales", "0002_pack"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("annale", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_set", to="annales.annale")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="users.user")),
            ],
            options={
                "unique_together": {("annale", "user")},
                "ordering": ["-created_at"],
            },
        ),
    ]
