# Generated by Django 5.1.4 on 2026-04-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annales', '0003_alter_pack_options_alter_pack_id'),
        ('annales', '0003_review'),
    ]

    operations = [
    ]
