# Generated by Django 5.1.4 on 2026-04-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annales', '0005_alter_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annale',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='annale',
            name='features',
            field=models.TextField(blank=True, help_text='Listez chaque élément sur une nouvelle ligne.', verbose_name='Ce que contient cette annale'),
        ),
    ]
