# Generated by Django 5.1.4 on 2026-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annales', '0006_remove_annale_is_popular_annale_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annale',
            name='features',
        ),
        migrations.AddField(
            model_name='annale',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
