# Generated by Django 5.1.4 on 2026-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annales', '0007_remove_annale_features_annale_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='annale',
            name='features',
            field=models.TextField(blank=True, help_text='Texte libre, markdown ou HTML autorisé.', verbose_name='Ce que contient cette annale'),
        ),
    ]
