# Generated by Django 3.2.25 on 2026-04-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
    ]
