# Generated by Django 5.1.4 on 2026-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
