# Generated by Django 5.1.4 on 2026-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('candidat', 'Candidat'), ('correcteur', 'Correcteur'), ('admin', 'Admin')], default='etudiant', max_length=20),
        ),
    ]
