# Generated by Django 5.1.4 on 2026-04-04 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='Ouvert', max_length=32)),
                ('image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
