# Generated by Django 5.1.4 on 2026-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='registration_url',
            field=models.URLField(blank=True),
        ),
    ]
