# Generated by Django 5.1.4 on 2026-04-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0002_concours_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='concours',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('upcoming', 'À venir')], default='open', max_length=32),
        ),
    ]
