# Generated by Django 5.1.4 on 2026-04-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0003_concours_is_urgent_alter_concours_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concours',
            name='is_urgent',
        ),
        migrations.AddField(
            model_name='concours',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions requises pour postuler (une condition par ligne)'),
        ),
    ]
